baseURL = "https://hiennguyen267.github.io/NguyenThiThuyHien_Blog/"
publishDir = "docs"
languageCode = "vi"
title = "NGUYEN THI THUY HIEN BLOG"
theme = "PaperMod"

# SỬA LẠI ĐOẠN NÀY
canonifyURLs = false
relativeURLs = false

[pagination]
  pagerSize = 3

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  # Thêm dòng này để fix lỗi asset
  env = "production" 

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang Chủ"
    url = "/" # Link tuyệt đối sẽ dựa vào baseURL
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Bài Viết"
    url = "posts/" # Hugo tự nối thành baseURL/posts/
    weight = 20